deploy/helm/chaosblade-operator/templates/deployment.yaml, exec/model/context.go, exec/model/executor.go, exec/pod/controller.go, exec/pod/delete.go, exec/pod/osexp.go
=> bugfix: fix the pod network experiment

Makefile, exec/model/controller.go, exec/model/controller_test.go, exec/node/controller.go, exec/pod/controller.go, go.mod, go.sum
See chaosblade-io/chaosblade#306
1. Fix percentage calculation logic.
2：Use `math.Round` function to get the percentage count.
```
percentCount := int(math.Round(float64(percent) / 100.0 * float64(resourceCount)))
if count > percentCount {
count = percentCount
}
if count > resourceCount {
return resourceCount, nil
}
return count, nil
```
1. Add unit test.
2. Run the following command to test in kubernetes cluster:
Get the number of nodes.
```
kubectl get node 
NAME                        STATUS   ROLES    AGE    VERSION
cn-hangzhou.192.168.0.100   Ready    <none>   128d   v1.14.8-aliyun.1
cn-hangzhou.192.168.0.98    Ready    <none>   128d   v1.14.8-aliyun.1
cn-hangzhou.192.168.0.99    Ready    <none>   128d   v1.14.8-aliyun.1
```
Execute node …
=> Fix the problem that evict-percent does not take effect

Makefile, build/Dockerfile, cmd/hookfs/main.go, cmd/webhook/main.go, deploy/oss/rbac.yaml, deploy/oss/webhook-cert-job.yaml, deploy/oss/webhook.yaml, exec/pod/controller.go, exec/pod/fsexp.go, exec/pod/pod.go, go.mod, go.sum, pkg/hookfs/client.go, pkg/hookfs/hook.go, pkg/hookfs/server.go, pkg/hookfs/types.go, pkg/webhook/add_admision.go, pkg/webhook/pod/pod_mutator.go, pkg/webhook/pod/pod_mutator_test.go, pkg/webhook/webhook.go
add pod file system I/O experiments
Fixes: https://github.com/chaosblade-io/chaosblade/issues/318
=> feat: add pod file system I/O experiments

exec/container/controller.go, exec/model/filter_pod.go, exec/model/model.go, go.mod, go.sum
Support dynamic container names. Use `container-index` to specify the container.
Add `--container-index` flag starting from 0.
```
blade c k8s container-cpu fullload --names frontend-6c887c56c8-4g7sh --container-index 0 --namespace default --kubeconfig ~/.kube/config
```
=> feature: add container-index flag for container chaos

exec/container/container.go, exec/node/node.go, exec/pod/delete.go, exec/pod/failexp.go, exec/pod/fsexp.go, exec/pod/pod.go, go.mod
improvement the action use case
#chaosblade 401
blade create k8s pod-file add -h
=> feature:improvement the action use case

build/Dockerfile, exec/model/executor.go
fix: use --timeout flag in k8s environment, blade resources cannot be released
#34 
Check the status, and release the blade automatically after the experiment is destroyed
=> fixbug: use --timeout flag in k8s environment

deploy/helm/chaosblade-operator-for-v2/templates/deployment.yaml, deploy/helm/chaosblade-operator-for-v2/values.yaml, deploy/helm/chaosblade-operator-for-v3/templates/deployment.yaml, deploy/helm/chaosblade-operator-for-v3/values.yaml, pkg/controller/chaosblade/controller.go, pkg/runtime/chaosblade/chaosblade.go
Periodically clean up invalid blade
#52
=> feature: Periodically clean up invalid blade

exec/model/executor.go, exec/model/parallelizer.go
The execution in matched pods with low efficiency
https://github.com/chaosblade-io/chaosblade-operator/issues/77
1. parallelize exec commands in matched pods
2. set max parallel count 64
```
apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
name: loss-pod-by-labels
spec:
experiments:
- scope: pod
target: network
action: loss
desc: "node network loss"
matchers:
- name: labels
value: ["app=nginx"]
- name: namespace
value: ["default"]
- name: percent
value: ["100"]
- name: interface
value: ["eth0"]
- name: local-port
value: ["80"]
```
=> parallelize exec command in matched pods

deploy/helm/chaosblade-operator-for-v2/templates/daemonset.yaml, deploy/helm/chaosblade-operator-for-v3/templates/daemonset.yaml, pkg/controller/chaosblade/controller.go
chaosblade-io/chaosblade#527
chaosblade-io/chaosblade#527
Add chaosblade-tool daemonset yaml file. Use `daemonset.enable` flag to control the daemonset deployment.
Default deployment:
```
helmv3 install chaosblade-operator deploy/helm/chaosblade-operator-for-v3 --namespace chaosblade --set operator.repository=registry.cn-hangzhou.aliyuncs.com/ahas/chaosblade-operator,operator.version=1.3.0-dev 
```
Disable daemonset deployment:
```
helmv3 install chaosblade-operator deploy/helm/chaosblade-operator-for-v3 --namespace chaosblade --set operator.repository=registry.cn-hangzhou.aliyuncs.com/ahas/chaosblade-operator,operator.version=1.3.0-dev,daemonset.enable=false
```
=> feature: expose chaosblade-tool daemonset yaml configuration

Makefile, build/Dockerfile, exec/container/container.go, exec/model/download.go, exec/model/executor.go, exec/model/model.go
1. `daemonset.enable` should not control how the container network scenario is implemented.
2. The sidecar implementation currently only supports docker containers.
3. Only used when the tc command does not exist in the target container.
Add `is-docker-network` flag to active sidecar implementation.
=> feature: add is-docker-network flag

Makefile, build/Dockerfile, deploy/helm/chaosblade-operator-for-v2/templates/deployment.yaml, deploy/helm/chaosblade-operator-for-v2/values.yaml, deploy/helm/chaosblade-operator-for-v3/templates/deployment.yaml, deploy/helm/chaosblade-operator-for-v3/values.yaml
1. add network setting in operator deployment.
2. optimize operator image build without operator-sdk(0.19.0) dependency.
3. fix chaosblade-operator build_yaml in chaosblade release build_all.
Fixes #111 
update Makefile and helm charts.
=> Build and deploy optimize

deploy/crds/chaosblade.io_chaosblades_crd.yaml, deploy/helm/chaosblade-operator-for-v2/templates/crd.yaml, deploy/helm/chaosblade-operator-for-v2/templates/rbac.yaml, deploy/helm/chaosblade-operator-for-v3/crds/crd.yaml, deploy/helm/chaosblade-operator-for-v3/templates/rbac.yaml
=> support 1.22 k8s

deploy/helm/chaosblade-operator/templates/daemonset.yaml, exec/model/executor.go
Use `container-label-selector` instead of `container-id` when destroying cri network experiment.
When simulating pod network fault, we should use the container label as a selector to select the sandbox container of the target pod instead of other containers in the target pod since container-id may change after pod restart.
As `chaosblade-exec-cri` needs to access `/var/run/netns` for the network namespace path of the sandbox container, we need to mount the host directory `/var/run/netns` in `chaosblade-tool` pod.
=> use container-label-selector instead of container-id when destroy cri network exp

exec/model/executor_nsexec.go
Signed-off-by: NigelWu95 <bingheng.wbh@antgroup.com>
#150
=> fix: ns common executor's destroy command for network experiment

Makefile, deploy/helm/chaosblade-operator-arm64/.helmignore, deploy/helm/chaosblade-operator-arm64/Chart.yaml, deploy/helm/chaosblade-operator-arm64/crds/crd.yaml, deploy/helm/chaosblade-operator-arm64/templates/NOTES.txt, deploy/helm/chaosblade-operator-arm64/templates/_helpers.tpl, deploy/helm/chaosblade-operator-arm64/templates/daemonset.yaml, deploy/helm/chaosblade-operator-arm64/templates/deployment.yaml, deploy/helm/chaosblade-operator-arm64/templates/rbac.yaml, deploy/helm/chaosblade-operator-arm64/templates/secret.yaml, deploy/helm/chaosblade-operator-arm64/templates/service.yaml, deploy/helm/chaosblade-operator-arm64/values.yaml
=> add arm64 helm chart, update verison from 1.6.0 to 1.6.1

exec/model/filter.go, exec/model/filter_pod.go, exec/node/filter.go
Signed-off-by: Icesource <gonghuajian.ghj@alibaba-inc.com>
Fix https://github.com/chaosblade-io/chaosblade/issues/770
Fixes https://github.com/chaosblade-io/chaosblade/issues/770
之前，匹配用的 标签都保存在一个Map中，这会导致如果指定了同key的多个标签，后来的value会覆盖原来的value。
例如，指定 app=a , app=b ，那么只有app=b会 生效
修改为直接使用 labels.Requirement 保存标签可以做到不覆盖，且可调用Selector.In来实现多个value值的或匹配
修改代码后使用以下pod进行验证
```
default       my-nginx-deployment-586df48455-c5str                       1/1     Running                  0          7m50s   app=mynginx,pod-template-hash=586df48455
default       my-nginx-deployment-586df48455-jlkmn                       1/1     Running                  0          14m     app=mynginx,pod-template-hash=586df48455
default       my2-nginx-deployment-6c67c949d9-kmzgw                      1/1     Running …
```
=> fix: kill k8s pod with multi labels not work

exec/container/controller.go
fix containerId getting when getting matched container to avoid nill pointer problem.
Signed-off-by: NigelWu95 <bingheng.wbh@antgroup.com>
#141
=> fix: get containerId when getting matched container

exec/model/executor.go
Change status.phase of chaosblade to 'Destroyed' when the experiment was destroyed,and therefore operator will not only delete CR of chaoblade,but avoid actually destroying experiment for the second time as well.
Fixes #203
=> fix:avoid duplicate deletion of experiment

exec/container/controller.go, exec/model/executor_copy.go
Remove unnessesary docker container id truncation, if user input a long container id, we can correctly match them.
Fix issue: https://github.com/chaosblade-io/chaosblade/issues/902
=> fix issue 902: chaosblade operator match containerId

exec/model/executor_nsexec.go
fix DNS Action Destroy Failed
Fixes [#962](https://github.com/chaosblade-io/chaosblade/issues/962)
Filter containers by labels when cri network target is destroyed
When the CRI network fails and is destroyed, the POD is filtered through the sandbox. This is to prevent the name of the POD from changing after it is restarted. However, the DNS scene will not be restarted, which will cause the DNS scene to fail to be destroyed.
=> fix: DNS Action Destroy Failed

Makefile
Image tags in makefile are wrong. 
NONE.
Replace all `chaosbladeio` with `chaosblade-io` of image tags.
=> fix: wrong docker image tag

Makefile, README.md, README_CN.md
Currently, there is a lack of documentation on how to build an operator and install it locally.
=> docs: Illustrate how to build operators locally

exec/model/executor_nsexec.go
fixed:https://github.com/chaosblade-io/chaosblade/issues/899
=> default scope cri

exec/model/filter_pod.go
Filter out TERMINATING pods(which have `deletionTimestamp`) before injecting chaos exp.
RESOLVE https://github.com/chaosblade-io/chaosblade/issues/1168
The `chaosblade-operator` currently lacks the conditions to write tests. But I have applied this patch in the PROD env of my team and served 200+ apps for experiments since 03/2025.
=> feat: filter out terminating pods from the pod list to inject exps

exec/model/executor_copy.go
Go to https://github.com/chaosblade-io/chaosblade/issues/1097 for details.
RESOLVE https://github.com/chaosblade-io/chaosblade/issues/1097
Remove redundant and unnecessary condition branch.
The `chaosblade-operator` currently lacks the conditions to write tests. But I have applied this patch to a internal fork ChaosBlade in the PROD env and served 200+ apps for experiments since 01/2025.
=> fix: unify biz to destroy network exp
