chaosblade-io/chaosblade-operator

- deploy/helm/chaosblade-operator/templates/deployment.yaml
- deploy/helm/chaosblade-operator/templates/rbac.yaml
- exec/model/context.go
- pkg/apis/chaosblade/meta/meta.go
- pkg/controller/chaosblade/daemonset.go
See #3 for the details.
1. Change default `kube-system` to `{{ .Release.Namespace }}` in helm yaml files.
2. Add `--namespace` flag in the operator to record the namespace.
> bugfix: support to specify namespace to deploy

- deploy/helm/chaosblade-operator/templates/deployment.yaml
- deploy/oss/daemonset.yaml
Fixes https://github.com/chaosblade-io/chaosblade/issues/263
> bugfix: add /etc/hosts volume

- exec/container/executor.go
- exec/pod/osexp.go
- go.mod
- go.sum
- pkg/apis/chaosblade/meta/meta.go
- pkg/controller/chaosblade/controller.go
chaosblade-io/chaosblade-exec-docker#3
Add `--image-repo` and `--image-version` flags for container experiments.
> feature: support to specify chaosblade-tool repository and version

- exec/node/osexp.go
- exec/pod/osexp.go
Fixes: https://github.com/chaosblade-io/chaosblade/issues/283
add mem and disk experiments for k8s
> feature: add mem and disk experiments for k8s

- channel/client.go
- exec/container/controller.go
- exec/container/executor.go
- exec/controller.go
- exec/model/controller.go
- exec/model/filter.go
- exec/pod/osexp.go
- go.mod
- go.sum
chaosblade-io/chaosblade#334
Modify the container experiments implementation.
Test Pod and Container experiments on k8s env.
> bugfix: fix cannot get output about docker experiments

- exec/model/filter_pod.go
- exec/model/filter_pod_test.go
- exec/pod/delete.go
See chaosblade-io/chaosblade#307 , #14 
1. Add `--random` flag.
2. Add the following function to select resources randomly:
```
func randomPodSelected(pods []v1.Pod, count int) []v1.Pod {
if len(pods) == 0 {
return pods
}
rand.Seed(time.Now().UnixNano())
for i := len(pods) - 1; i > 0; i-- {
num := rand.Intn(i + 1)
pods[i], pods[num] = pods[num], pods[i]
}
return pods[:count]
}
```
1. Add function unit test.
2. Run it on kubernetes cluster.
First Run:
```
"resStatuses": [
{
"id": "1c11da5b6a3f69fc",
"kind": "node",
"name": "cn-hangzhou.192.168.0.98",
"nodeName": "cn-hangzhou.192.168.0.98",
"state": "Success",
"success": true,
"uid": "f42d26fd-f92c-11e9-b177-7e85fdbc41e3"
},
{
"id": "8a5ceeba7aa50dda",
"kind": "node",
"name": …
```
> Randomly select resources from the filter results

- exec/pod/osexp.go
- go.mod
- go.sum
````
vi append_file.yaml
````
````
apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
name: append-file-v2
spec:
experiments:
- scope: container
target: file
action: append
desc: "append file pod logs by names"
matchers:
- name: container-names
value:
- "redis"
- name: names
value:
- "frontend-xx"
- name: namespace
value:
- "default"
- name: filepath
value: ["/tmp/tmp.log"]
- name: content
value: ["@{DATE:+%Y-%m-%d %H:%M:%S} ERROR cba @{RANDOM:100-200} abc  mock exception"]
````
````
kubectl apply -f append_file.yaml
````
> feature:support append file, chmod file

- exec/node/node.go
- go.mod
chaosblade 403 
`blade create k8s node-cpu load --cpu-percent 60 --channel ssh --ssh-host 101.37.30.161  --ssh-user root`
> feature:add ssh channel for node

- build/Dockerfile
- go.mod
- go.sum
Reduce the operator image size , use docker multi-stage builds
#39
> feature: Reduce the operator image size

- exec/container/container.go
- exec/node/node.go
- exec/pod/delete.go
- exec/pod/pod.go
- go.mod
- go.sum
https://github.com/chaosblade-io/chaosblade/issues/427
> feature: improvement use case

- cmd/manager/main.go
- deploy/helm/chaosblade-operator-for-v2/values.yaml
- deploy/helm/chaosblade-operator-for-v3/values.yaml
- pkg/controller/chaosblade/controller.go
- pkg/runtime/runtime.go
Support concurrent execution.
Add `qps` and `reconcile.count` flag to specify number of concurrent executions. Default values are 20.
> feature: add qps and reconcile count configs

- deploy/helm/chaosblade-operator-for-v2/templates/rbac.yaml
- deploy/helm/chaosblade-operator-for-v3/templates/rbac.yaml
- exec/controller.go
- exec/model/controller.go
- exec/model/executor.go
- exec/model/filter.go
- exec/model/filter_pod.go
- exec/node/controller.go
- exec/node/filter.go
- exec/node/node.go
recover node daemonset
````
blade create k8s node-cpu load -h
blade create k8s node-cpu load --names izbp1a4jchbdwkwi5hk7ekz --kubeconfig ~/.kube/config --timeout 30
````
> Recover node daemonset

- exec/model/executor.go
> fix chaosblade resource status

- Makefile
- deploy/helm/chaosblade-operator-for-v2/Chart.yaml
- deploy/helm/chaosblade-operator-for-v2/values.yaml
- deploy/helm/chaosblade-operator-for-v3/Chart.yaml
- deploy/helm/chaosblade-operator-for-v3/values.yaml
- exec/model/category.go
- exec/model/executor.go
- exec/pod/delete.go
- exec/pod/failexp.go
- exec/pod/fsexp.go
- go.mod
- go.sum
> Release v0.10.0

- examples/pod-cpu-load-by-names.yml
Signed-off-by: he.qingguo he.qingguo@zte.com.cn
Describe what this PR does / why we need it
Rich sample library
Does this pull request fix one issue?
#65
Describe how you did it
add some yaml file
Describe how to verify it
you can run the command:
kubectl apply -f xxxx.yml
Special notes for reviews
> add example for pod-cpu-load

- examples/node-cpu-load.yml
- examples/node-disk-load-burn-read.yml
- examples/node-disk-load-burn-write.yml
- examples/node-disk-load-fill.yml
- examples/node-mem-load.yml
- examples/node-network-delay-by-names.yml
- examples/node-network-loss-by-names.yml
Signed-off-by: he.qingguo <he.qingguo@zte.com.cn>
Rich sample library
https://github.com/chaosblade-io/chaosblade-operator/issues/65
add some yaml file
you can run the command:
kubectl apply -f xxxx.yml
> add example for node.

- examples/node-cpu-load.yml
- examples/node-disk-load-burn-read.yml
- examples/node-disk-load-burn-write.yml
- examples/node-disk-load-fill.yml
- examples/node-mem-load.yml
- examples/node-network-delay-by-names.yml
- examples/node-network-loss-by-names.yml
- examples/pod-cpu-load-by-names.yml
- examples/pod-delete_by_names.yaml
Signed-off-by: he.qingguo <he.qingguo@zte.com.cn>
> Optimized Sample Name

- Makefile
- channel/client.go
- exec/container/controller.go
- exec/model/controller.go
- exec/model/copy.go
- exec/model/executor.go
- exec/model/filter.go
- exec/model/filter_pod.go
- exec/node/controller.go
- exec/node/filter.go
- exec/pod/controller.go
- exec/pod/delete.go
- exec/pod/failexp.go
- exec/pod/fsexp.go
- go.mod
- pkg/apis/chaosblade/v1alpha1/types.go
At present, the error codes of the replies are messy, which requires unified and refactoring.
Fixes chaosblade-io/chaosblade#489
Unified error code structure and error content
> Unified error code

- Makefile
- channel/client.go
- exec/container/controller.go
- exec/model/controller.go
- exec/model/copy.go
- exec/model/executor.go
- exec/model/filter.go
- exec/model/filter_pod.go
- exec/node/controller.go
- exec/node/filter.go
- exec/pod/controller.go
- exec/pod/delete.go
- exec/pod/failexp.go
- exec/pod/fsexp.go
- go.mod
- go.sum
- pkg/apis/chaosblade/v1alpha1/types.go
when k8s environment, Upload error code from the bottom up. update version
> V1.1.0 dev

- .gitignore
- Makefile
- exec/model/executor.go
- go.mod
- go.sum
> V1.2.0 dev

- deploy/helm/chaosblade-operator-for-v2/Chart.yaml
- deploy/helm/chaosblade-operator-for-v2/values.yaml
- deploy/helm/chaosblade-operator-for-v3/Chart.yaml
- deploy/helm/chaosblade-operator-for-v3/values.yaml
- exec/model/executor.go
- go.sum
fix: copy chaos_os bin & update charts version to 1.2.0
> fix: copy chaos_os bin & update charts version to 1.2.0

- Makefile
- exec/model/executor.go
- go.mod
- go.sum
chaosblade-io/chaosblade#522
1. Add `container-name` flag in chaosblade-io/chaosblade-exec-docker project. See chaosblade-io/chaosblade-exec-docker#18
> Support for using container-name to execute container experiments

- exec/model/executor.go
- exec/model/model.go
- go.mod
- go.sum
chaosblade-io/chaosblade#523
Made some changes:
1. `chaosblade-deployed-path`  -> `chaosblade-path`
2. `blade-tar-file` -> `chaosblade-release`
3. `blade-override` -> `chaosblade-override`
> feature: standardize chaosblade deployment parameters

- Makefile
- exec/container/application.go
- go.sum
Adjust the priority of downloading the chaosblade package
> chore: optimize make script

- exec/model/executor.go
- go.sum
Fix the previous version code error.
> bugfix: fix chaosblade deployed processing

- exec/model/executor.go
- go.mod
- go.sum
1. Fix operation with `--async` flag.
2. Modify the code of chaosblade deployed.
3. Fix the judgement logic executed in the pod.
> bugfix: fix async operation

- exec/model/executor_nsexec.go
fix: nsexec for stress experiment
> fix: nsexec for stress experiment

- Makefile
> chore: support compile of arm64

- build/Dockerfile
- deploy/helm/chaosblade-operator-arm64/templates/deployment.yaml
- deploy/helm/chaosblade-operator/templates/deployment.yaml
> Undepends on blade binaries

- exec/node/node.go
- exec/pod/pod.go
Signed-off-by: Yuaninga <1846225041@qq.com>
> add node and pod about file exprient examples

- exec/node/node.go
Signed-off-by: Yuaninga <1846225041@qq.com>
> feat: add node file

- .github/workflows/upload_chart.yml
Signed-off-by: caimingxia <mingshao.cmx@alibaba-inc.com>
> add github action for upload chart to oss

- Makefile
- build/image/amd/Dockerfile
- build/image/arm/Dockerfile
Fix problems in arm architecture compilation
use buildx  command
> fix:arm64 compilation

- build/image/amd/Dockerfile
- build/musl/Dockerfile
> fix: upgrade deprecated image tag
